# Generated by Django 6.1.1 on 2026-09-13 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('journaling', 'Journaling'), ('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('supplement', 'Supplement'), ('sleep', 'Sleep'), ('mood', 'Mood'), ('screen_time', 'Screen Time'), ('study', 'Study'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('goal_value', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('value', models.FloatField(blank=True, null=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tasks.habit')),
            ],
        ),
    ]
