# Generated by Django 6.1.1 on 2026-09-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_habit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_numeric',
            field=models.BooleanField(default=False),
        ),
    ]
